# Generated by Django 3.0.4 on 2020-05-18 14:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalDetails',
            fields=[
                ('hospitalId', models.UUIDField(primary_key=True, serialize=False)),
                ('Resources', multiselectfield.db.fields.MultiSelectField(choices=[('R1', 'Ambulatory surgical center'), ('R2', 'Birth center'), ('R3', 'Dialysis Center')], default='R1', max_length=8)),
                ('vacancy', models.BigIntegerField(default=0)),
                ('HospitalName', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_beds', models.IntegerField(default=0)),
                ('total_nonMed_staff', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDetails',
            fields=[
                ('DocId', models.UUIDField(primary_key=True, serialize=False)),
                ('Name', models.TextField()),
                ('VisitingHoursFrom', models.TimeField(default=django.utils.timezone.now)),
                ('VisitingHoursTo', models.TimeField(default=django.utils.timezone.now)),
                ('hospitalId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.HospitalDetails')),
            ],
        ),
    ]
