# Generated by Django 3.0.4 on 2020-05-19 13:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('lat', models.IntegerField()),
                ('long', models.IntegerField()),
                ('illnesses', multiselectfield.db.fields.MultiSelectField(choices=[('I1', 'Measles'), ('I2', 'Typhoid'), ('I3', 'Malaria'), ('I4', 'Flu')], default=None, max_length=11)),
                ('currentPrescriptions', models.TextField()),
                ('isAdmitted', models.BooleanField(default=None)),
                ('pId', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='ResourceDetails',
        ),
        migrations.RenameField(
            model_name='doctordetails',
            old_name='DocId',
            new_name='dId',
        ),
        migrations.RenameField(
            model_name='doctordetails',
            old_name='VisitingHoursFrom',
            new_name='hospShiftEnd',
        ),
        migrations.RenameField(
            model_name='doctordetails',
            old_name='VisitingHoursTo',
            new_name='hospShiftStart',
        ),
        migrations.RenameField(
            model_name='doctordetails',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='doctordetails',
            name='hospitalId',
        ),
        migrations.RemoveField(
            model_name='hospitaldetails',
            name='HospitalName',
        ),
        migrations.RemoveField(
            model_name='hospitaldetails',
            name='Resources',
        ),
        migrations.RemoveField(
            model_name='hospitaldetails',
            name='vacancy',
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='hId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Registration.HospitalDetails'),
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='lat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='long',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='visEnd',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='visStart',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hospitaldetails',
            name='ResourceToQuant',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitaldetails',
            name='dId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Registration.DoctorDetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitaldetails',
            name='lat',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitaldetails',
            name='long',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='hId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Registration.HospitalDetails'),
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='patientId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Registration.Patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitaldetails',
            name='pId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Registration.Patient'),
            preserve_default=False,
        ),
    ]
