# Generated by Django 3.0.4 on 2020-05-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_auto_20200524_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='idno',
            name='name',
            field=models.CharField(default=None, max_length=90),
            preserve_default=False,
        ),
    ]
