# Generated by Django 3.0.4 on 2020-05-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_auto_20200519_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetails',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
