# Generated by Django 3.0.4 on 2020-05-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_idno_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaldetails',
            name='ResourceToQuant',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hospitaldetails',
            name='dId',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='currentPrescriptions',
            field=models.CharField(max_length=500),
        ),
    ]
