# Generated by Django 3.0.4 on 2020-05-19 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_auto_20200519_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetails',
            name='patientId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Registration.Patient'),
        ),
        migrations.AlterField(
            model_name='hospitaldetails',
            name='dId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Registration.DoctorDetails'),
        ),
        migrations.AlterField(
            model_name='hospitaldetails',
            name='lat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hospitaldetails',
            name='long',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hospitaldetails',
            name='pId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Registration.Patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Registration.HospitalDetails'),
        ),
    ]
