# Generated by Django 3.0.4 on 2020-05-19 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0004_auto_20200519_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetails',
            name='hId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Registration.HospitalDetails'),
        ),
        migrations.AlterField(
            model_name='doctordetails',
            name='patientId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Registration.Patient'),
        ),
        migrations.AlterField(
            model_name='hospitaldetails',
            name='dId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Registration.DoctorDetails'),
        ),
        migrations.AlterField(
            model_name='hospitaldetails',
            name='pId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Registration.Patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Registration.HospitalDetails'),
        ),
    ]
