# Generated by Django 3.0.4 on 2020-05-24 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0004_auto_20200524_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitaldetails',
            old_name='ResourceToQuant',
            new_name='ResourceQuantity',
        ),
        migrations.RenameField(
            model_name='hospitaldetails',
            old_name='dId',
            new_name='doctorIds',
        ),
        migrations.RenameField(
            model_name='hospitaldetails',
            old_name='pId',
            new_name='patientIds',
        ),
    ]
