# Generated by Django 3.0.4 on 2020-05-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0005_auto_20200519_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetails',
            name='dId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hospitaldetails',
            name='hospitalId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
