# Generated by Django 3.0.4 on 2020-05-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0006_auto_20200519_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitaldetails',
            name='dId',
        ),
        migrations.AddField(
            model_name='hospitaldetails',
            name='dId',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='_hospitaldetails_dId_+', to='Registration.DoctorDetails'),
        ),
    ]
