# Generated by Django 3.0.4 on 2020-05-19 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0007_auto_20200520_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitaldetails',
            name='dId',
        ),
        migrations.AddField(
            model_name='hospitaldetails',
            name='dId',
            field=models.ForeignKey(blank=True, default=None, max_length=4, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Registration.DoctorDetails'),
        ),
    ]
