# Generated by Django 3.0.4 on 2020-05-21 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0008_auto_20200520_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetails',
            name='patientId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Registration.patient'),
        ),
        migrations.AlterField(
            model_name='hospitaldetails',
            name='pId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Registration.patient'),
        ),
    ]
